name: image_search_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.1.1
  flutter_dotenv: ^5.0.2
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.8.1
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.3.0 <4.0.0'

  flutter_lints: ^3.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'

  json_serializable: ^6.6.2

flutter:

  uses-material-design: true

  assets:
    - assets/config/.env
    - assets/image/
